#
# The resulting image of this Dockerfile would have oracle linux and oracle weblogic 1221  and osb1221 installed
#
# REQUIRED FILES TO BUILD THIS IMAGE
# ----------------------------------
# (1) osb_generic.jar
#     Copy this file from shiphome location and keep it in directory where docker file is created
#
#
# HOW TO BUILD THIS IMAGE
# -----------------------
# Put all downloaded files in the same directory as this Dockerfile
# Run:
#
# docker build --force-rm=true --no-cache=true --rm=true -t oracle/osb:1221 .
#
# Pull base image
# ---------------
FROM oracle/weblogic:12.2.1.2-infrastructure
#
#
# Maintainer
# ----------
MAINTAINER Shuxuan Nie <judy.nie@oracle.com>
#
# Set the environment values
# -----------------------------------------
#
#

ENV OSB_PKG fmw_12.2.1.2.0_osb.jar

#
# Copy packages
#-----------------------
ADD $OSB_PKG /u01/
ADD container-scripts /u01/oracle/container-scripts/
COPY osbinstall.file /u01/
COPY oraInst.loc /u01/

# ----------------------------------
# Expose ports
# ----------------------------------
ENV OSB_PORT 8011
EXPOSE $OSB_PORT
#

# install OSB required rpm packages:
RUN yum install  -y \
        compat-libstdc++-33 \
        unzip \
        libXext \
        libXtst \
        libXrender \
        tar \
        make \
        xdpyinfo \
        nfs-utils \
        binutils \
        compat-libcap1 \
        gcc \
        gcc-c++ \
        glibc-2.12-1.80.el6 \
        glibc \
        ksh \
        libaio \
        libaio-devel \
        libgcc \
        libstdc++

# Installation of osb

RUN cd /u01 && \
    su oracle -c "$JAVA_HOME/bin/java -jar /u01/$OSB_PKG -novalidation -silent -responseFile /u01/osbinstall.file -invPtrLoc /u01/oraInst.loc -jreLoc $JAVA_HOME" && \
    rm -fr /u01/$OSB_PKG /u01/osbinstall.file /u01/oraInstl.loc


USER oracle
WORKDIR /u01/oracle/
#
#
#
ENV PATH $PATH:/u01/oracle/weblogic/oracle_common/common/bin
#
# Define default command to start bash.
CMD ["/u01/oracle/createAndStartOSBDomain.sh"]