#
# The resulting image of this Dockerfile would have oracle linux and oracle weblogic 1221  and soa 1221 installed
#
#
# Pull base image
# ---------------
FROM oracle/weblogic:12.2.1.2-infrastructure
#
#
# Maintainer
# ----------
MAINTAINER Shuxuan Nie <judy.nie@oracle.com>
#
# Set the environment values
# -----------------------------------------
#
#

ENV SOA_PKG fmw_12.2.1.2.0_soa.jar

#
# Copy packages
#-----------------------
ADD $SOA_PKG /u01/
COPY soainstall.file /u01/
COPY oraInst.loc /u01/

# ----------------------------------
# Expose ports
# ----------------------------------
ENV SOA_PORT 8001
EXPOSE $SOA_PORT
#

# install SOA required rpm packages:
RUN yum install  -y \
        compat-libstdc++-33 \
        unzip \
        libXext \
        libXtst \
        libXrender \
        tar \
        make \
        xdpyinfo \
        nfs-utils \
        binutils \
        compat-libcap1 \
        gcc \
        gcc-c++ \
        glibc-2.12-1.80.el6 \
        glibc \
        ksh \
        libaio \
        libaio-devel \
        libgcc \
        libstdc++

# Installation of soa

RUN cd /u01 && \
    su oracle -c "$JAVA_HOME/bin/java -jar /u01/$SOA_PKG -novalidation -silent -responseFile /u01/soainstall.file -invPtrLoc /u01/oraInst.loc -jreLoc $JAVA_HOME" && \
    rm -fr /u01/$SOA_PKG /u01/soainstall.file /u01/oraInstl.loc


USER oracle
WORKDIR /u01/oracle/
#
#
#
ENV PATH $PATH:/u01/oracle/weblogic/oracle_common/common/bin
#
# Define default command to start bash.
CMD ["bash"]
